spring:
  profiles:
    active: develop

---
spring:
  profiles: develop
server:
  port: 8081
  servlet:
    context-path: /platzi-market/api/develop

---
spring:
  profiles: qa
server:
  port: 8082
  servlet:
    context-path: /platzi-market/api/qa
---
spring:
  profiles: production
server:
  port: 8083
  servlet:
    context-path: /platzi-market/api/prod